### ISSUE TITLE
ウォーターサーバーについて

### ISSUE THREAD

**Issue by sinmuraharuna** [icat-lab/ay2021autumn_Hakuba#3]
プレゼン資料を見て、費用が気になりました。学校が負担する以外で資金を集める方法を考えると、校内での募金活動やクラウドファンディングが思いつきました。それ以外に思ったことをまとめました。

# マイボトルで地球環境も地域経済も
#### マイボトルを村内のカフェ対応させる
* 元々マイボトルを推奨しているカフェに生徒たちが対応するのか、それともカフェにマイボトル制度を導入してもらうのか？
                       ↓
* 店側にとっての利点を説明するとスムーズに対応していただけると思うので、カフェに対応していただくためにはどのように説明をする？店側のメリットは？
* 対応してもらうカフェの数はどのくらいか？
# 白馬の水を白馬の魅力へ
* 自販機のドリンクより水道水を飲みたくなるような白馬の水の魅力が伝われば、生徒たちのマイボトルの普及が広まると思うので、具体的な白馬の水の特徴は？他の水道水と違う所は？

**Comment by daikichi0609** [comment]
https://github.com/icat-lab/ay2021autumn_Hakuba/issues/18
https://github.com/icat-lab/ay2021autumn_Hakuba/issues/19
上記2つのissueに分けたので、このissueはcloseする。
